# Generated by Django 4.1.4 on 2023-03-14 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Message', models.IntegerField()),
                ('email', models.EmailField(max_length=20)),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
