# Generated by Django 4.1.7 on 2023-03-14 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_form'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='Message',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='Name',
            new_name='name',
        ),
    ]
