# Generated by Django 4.1.7 on 2023-03-14 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_rename_message_form_message_rename_name_form_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='message',
            field=models.CharField(max_length=40),
        ),
    ]
